name: Compile LaTeX Files

on:
  push:
    paths:
      - 'output/**/*.pdf'
  pull_request:
    paths:
      - 'output/**/*.pdf'
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Create Output Directory
        run: mkdir -p output          

      - name: Generate Booklet PDFs
        run: |
          for pdf in output/*- View.pdf; do
            base_name=$(basename "$pdf" " - View.pdf")
            pdfjam --booklet true --landscape --paper a4paper "$pdf" --outfile "output/${base_name} - Print.pdf"
          done  

      - name: Delete Temporary LaTeX Files
        run: rm -f output/*.{aux,log,lof,lot,toc,bbl,blg,out,synctex.gz,fdb_latexmk,fls,bcf,run.xml}

      - name: Auto Commit PDFs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Compiled LaTeX files with View and Print versions"
          push_options: '--force'
          file_pattern: 'output/*.pdf'

      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: compiled-and-booklet-pdfs
          path: output/*.pdf
