name: Generate Booklet PDFs

on:
  push:
    paths:
      - 'output/**/*.pdf'
  pull_request:
    paths:
      - 'output/**/*.pdf'
  workflow_dispatch:

jobs:
  generate-booklets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install PDF Processing Tools
        run: |
          sudo apt update
          sudo apt install -y texlive-extra-utils

      - name: Process PDF Files
        run: |
          mkdir -p output
          for file in output/* - View.pdf; do
            if [[ -f "$file" ]]; then
              base_name="${file% - View.pdf}"
              pdfbook2 "$file"
              mv output.pdf "${base_name} - Print.pdf"
            fi
          done

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add output/* - Print.pdf
          git commit -m "Generate booklet PDFs"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  
